#! /bin/sh

polybar main &
xsetroot -cursor_name left_ptr &
/usr/lib/policykit-1-gnome/polkit-gnome-authentication-agent-1 &
xset r rate 300 50 &
xset mouse 5 1 &
xinput set-prop "SynPS/2 Synaptics TouchPad" "libinput Tapping Enabled" 1 &
xrandr --output LVDS-1 --brightness 0.9 &
nm-applet &
pasystray &
picom &
copyq &

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         0
bspc config window_gap          0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config pointer_follows_focus true
bspc config focus_follows_pointer true

bspc rule -a Gimp-2.10 desktop='^8' state=floating follow=on
bspc rule -a Firefox-esr desktop='^9'
bspc rule -a mpv state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

